[general]
live_config_reload = true
working_directory = "/Users/phuc/Projects/"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/bash"

[colors.primary]
background = "0xfafafa"
foreground = "0x4b505b"

[colors.normal]
black   = "0x4b505b"
red     = "0xd05858"
green   = "0x608e32"
yellow  = "0xbe7e05"
blue    = "0x5079be"
magenta = "0xb05ccc"
cyan    = "0x3a8b84"
white   = "0xfafafa"

[colors.bright]
black   = "0x4b505b"
red     = "0xd05858"
green   = "0x608e32"
yellow  = "0xbe7e05"
blue    = "0x5079be"
magenta = "0xb05ccc"
cyan    = "0x3a8b84"
white   = "0xfafafa"

[colors.cursor]
text   = "0xbe7e05"
cursor = "0xF9A825"

[font]
size = 19

[font.normal]
family = "Consolas 7NF"

[font.offset]
x = 0
y = 2

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
# startup_mode = "Maximized"
dynamic_padding = true
resize_increments = true
title = ""

[window.padding]
x = 0
y = 0

[window.position]
x = 800
y = 160

[window.dimensions]
columns = 175
lines = 49

