live_config_reload = true
working_directory = "/Users/phuc/Projects/"

[colors.primary]
background = '0x32302f'
foreground = '0xd4be98'

[colors.normal]
black   = '0x45403d'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[colors.bright]
black   = '0x45403d'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[colors.cursor]
text   = "0xbe7e05"
cursor = "0xF9A825"

[font]
size = 18

[font.normal]
family = "Consolas Nerd Font"

[font.offset]
x = 1
y = 8

[font.glyph_offset]
x = 1
y = 4

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "Return"
mods = "Alt"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/bash"

[window]
# startup_mode = "Maximized"
decorations_theme_variant = "dark"
dynamic_padding = true
resize_increments = true
title = ""

[window.padding]
x = 0
y = 0

[window.position]
x = 700
y = 150

[window.dimensions]
columns = 135
lines = 39

